%% STUDENT DETAILS:

% OLONISAKIN DAVID

% 18CK024244

% ELECTRICAL AND ELECTRONICS ENGINEERING

% EEE515

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Pavilion\28BusLineData.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 31-Oct-2022 14:19:21

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:D34";

% Specify column names and types
opts.VariableNames = ["BusFrom", "BusTo", "R", "X"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
BusLineData = readtable("C:\Users\Pavilion\Downloads\Telegram Desktop\28BusLineData.xlsx", opts, "UseExcel", false);

%% Convert to output type
BusLineData = table2array(BusLineData);


%% CODE: YBus28.m

f = BusLineData(:, 1); %  first vector column of the bus number (e.g bus from 1 -...)
t = BusLineData(:, 2); %  second vector column of the bus number(e.g bus to ... - 2)
r = BusLineData(:, 3); %  third vector column of the bus number
x = BusLineData(:, 4); %  fourth vector column of the bus number
nL = length(f); %  length of row (branches)
nBUS_length_column = max(max(f), max(t)); % no of buses; note: branches X bus
% Z = R+jX

Z = r + 1j*x; %1j and j are the same
y =  1./Z; 
Y_bus = zeros(nL, nBUS_length_column);
%initialize Y_bus to Z;
for k = 1:nL
    Y_bus(f(k), t(k)) = Y_bus(f(k),t(k))-y(k); % use of f(index) for indexing
    Y_bus(t(k), f(k)) = Y_bus(f(k),t(k));
    
end

for n = 1:nBUS_length_column
    for k = 1:nL
        if f(k) == n
            Y_bus(n,n) = Y_bus(n,n) + y(k);
        else
            if t(k) == n
                Y_bus(n,n) = Y_bus(n,n) + y(k);
            end
        end
    end
end
Y_bus
